@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Диаграмма контейнеров "Передача ставок в кол-центр"

Person(Клиент, "Клиент банка", "Физическое лицо, интересующееся условиями депозитов")
Person(Оператор_банка, "Оператор кол-центра", "Внутренний сотрудник банка")
Person_Ext(Оператор_партнера, "Оператор партнерского кол-центра", "Внешний сотрудник компании-партнера")

System_Boundary(Банковские_системы, "Банк «Стандарт»") {
    ContainerDb(Справочник_ставок, "Справочник ставок", "Oracle", "Хранит актуальные ставки по депозитам с учетом сегмента клиента")

    Container(Сервис_ставок, "Сервис управления ставками", "Java Spring Boot", "Обеспечивает API для работы со ставками и выгрузки данных")
    Container(Кол_центр_банка, "Кол-центр внутри банка", "Java, React", "CRM-система для обработки клиентских запросов")
    Container(Файловый_шлюз, "Файловый шлюз", "Linux, SFTP", "Обеспечивает безопасный обмен файлами с партнерами")
}

Container_Ext(Кол_центр_партнера, "Кол-центр партнера", "Внешняя система партнера", "CRM-система для обработки клиентских запросов")

Rel(Клиент, Кол_центр_банка, "Консультируется по условиям вкладов", "Телефонный звонок")
Rel(Клиент, Кол_центр_партнера, "Консультируется по условиям вкладов", "Телефонный звонок")
Rel(Оператор_банка, Кол_центр_банка, "Работает с клиентскими запросами", "HTTPS")
Rel(Оператор_партнера, Кол_центр_партнера, "Работает с клиентскими запросами", "HTTPS")
Rel(Кол_центр_банка, Сервис_ставок, "Синхронизация информации о ставках", "HTTPS")
Rel(Кол_центр_партнера, Файловый_шлюз, "Получение файлов со ставками", "SFTP, каждые 5 минут")
Rel(Сервис_ставок, Файловый_шлюз, "Получение подтверждения получения файла партнером", "SFTP, каждые 5 минут")

Rel(Сервис_ставок, Справочник_ставок, "Чтение/запись ставок", "JDBC")
Rel(Сервис_ставок, Файловый_шлюз, "Выгрузка ставок для партнеров (в формате CSV)", "SFTP, каждые 5 минут")

@enduml
